// tslint:disable:max-line-length
import { compact } from "lodash";

const buildCommand = (name: string) => `  build: coerceFactory<t.${name}>(s.${name}Factory, s.${name}Schema),`;
const coerceCommand = (name: string) => `  coerce: coerceValue<t.${name}>(s.${name}Schema),`;

const imports = (optionTypes: boolean, importCoerceFactory: boolean, libraryPath: string, schemasPath: string, typesPath: string) => [
  `import { ${importCoerceFactory ? "coerceFactory, " : ""}coerceValue } from "${libraryPath}";`,
  `import * as s from "${schemasPath}";`,
  `import * as t from "${typesPath}";`,
].join(`\n`);

export const baseTemplate = (optionTypes: boolean, importCoerceFactory: boolean, libraryPath: string, schemasPath: string, typesPath: string) => compact([
  `// tslint:disable:ordered-imports max-line-length`,
  `// THIS FILE IS GENERATED BY JOI-TS-GENERATOR. ANY CHANGES MADE WILL BE LOST.`,
  imports(optionTypes, importCoerceFactory, libraryPath, schemasPath, typesPath),
]).join(`\n\n`);

export default (name: string, hasFactory: boolean) =>
  compact([
    `export const ${name}Utils = {`,
    hasFactory ? buildCommand(name) : null,
    coerceCommand(name),
    "};",
  ]).join("\n");
